# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NnKHfpo5Fm3LvcNd8OgB_JAsTdfOWjSk
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)
plt.rcParams['figure.figsize'] = (10, 5)
plt.rcParams['font.size'] = 12

print("hii")

df=pd.read_csv("/content/attendance_survey.csv")

df.head(10)

df.tail()

print(f"Total Students  : {len(df)}")
print(f"Columns         : {df.columns.tolist()}")
print(f"\nMarks Range     : {df['marks_pct'].min()} – {df['marks_pct'].max()}")
print(f"Avg Marks       : {df['marks_pct'].mean():.1f}")
print(f"Avg Attendance  : {df['attendance_pct'].mean():.1f}%")

fig, ax = plt.subplots()

ax.hist(df['marks_pct'], bins=12,
        color='steelblue', edgecolor='white', linewidth=1.2)

ax.axvline(df['marks_pct'].mean(), color='red',
           linestyle='--', linewidth=2,
           label=f"Average: {df['marks_pct'].mean():.1f}")

ax.axvline(df['marks_pct'].median(), color='orange',
           linestyle='--', linewidth=2,
           label=f"Median: {df['marks_pct'].median():.1f}")

ax.set_title('How Are Marks Distributed?',
             fontsize=14, fontweight='bold')
ax.set_xlabel('Marks %')
ax.set_ylabel('Number of Students')
ax.legend()
plt.tight_layout()
plt.show()

fig, ax = plt.subplots(figsize=(10, 6))

ax.scatter(df['attendance_pct'], df['marks_pct'],
           color='steelblue', s=80, alpha=0.7, edgecolors='navy')

# Trend line
z = np.polyfit(df['attendance_pct'], df['marks_pct'], 1)
p = np.poly1d(z)
x_line = np.linspace(55, 100, 100)
ax.plot(x_line, p(x_line), 'r--', linewidth=2.5, label='Trend')

ax.set_title('Does Attendance Affect Marks?',
             fontsize=14, fontweight='bold')
ax.set_xlabel('Attendance %', fontsize=12)
ax.set_ylabel('Marks %', fontsize=12)
ax.legend(fontsize=11)
plt.tight_layout()
plt.show()

r = df['attendance_pct'].corr(df['marks_pct'])
print(f"Correlation : {r:.2f}")
print(f"Verdict     : {'Strong relationship ↑' if r > 0.6 else 'Moderate relationship' if r > 0.3 else 'Weak — something else is going on'}")

# Student with highest attendance but NOT the topper
high_attend = df.nlargest(3, 'attendance_pct')[
    ['attendance_pct', 'pays_attention', 'takes_notes', 'marks_pct']
]
print("TOP 3 ATTENDERS:")
print(high_attend.to_string(index=False))

print()

# Student with highest marks
high_marks = df.nlargest(3, 'marks_pct')[
    ['attendance_pct', 'pays_attention', 'takes_notes', 'marks_pct']
]
print("TOP 3 SCORERS:")
print(high_marks.to_string(index=False))

sit_avg = df.groupby('sits_where')['marks_pct'].mean().reindex(['Front','Middle','Back'])

fig, ax = plt.subplots(figsize=(8, 5))
colors = ['#2ecc71', '#f39c12', '#e74c3c']
bars = ax.bar(sit_avg.index, sit_avg.values,
              color=colors, edgecolor='black', width=0.5)

ax.set_title('Where You Sit → What You Score',
             fontsize=14, fontweight='bold')
ax.set_ylabel('Average Marks %')
ax.set_ylim(0, 100)

for bar in bars:
    ax.text(bar.get_x() + bar.get_width()/2,
            bar.get_height() + 1.5,
            f'{bar.get_height():.1f}%',
            ha='center', fontsize=13, fontweight='bold')

plt.tight_layout()
plt.show()

front = sit_avg['Front']
back  = sit_avg['Back']
print(f"Front avg  : {front:.1f}")
print(f"Back avg   : {back:.1f}")
print(f"Difference : {front - back:.1f} marks just by changing your seat")

# Install it
!pip install ydata-profiling -q

from ydata_profiling import ProfileReport

df = pd.read_csv('/content/attendance_survey.csv')

# ONE LINE — full EDA report
profile = ProfileReport(df, title="Attendance Survey Report",
                            explorative=True)
#display
profile.to_notebook_iframe()

!pip install sweetviz -q
import sweetviz as sv
high_scorers = df[df['marks_pct'] >= 60]
low_scorers  = df[df['marks_pct'] <  60]

# Compare them — ONE LINE
report = sv.compare([high_scorers, "High Scorers"],
                    [low_scorers,  "Low Scorers"])

report.show_notebook()

!pip install lux-api -q
import lux

df.intent = ['marks_pct', 'attendance_pct']
df

def print_sum(a,b,c):
  return a+b+c

# Extracting the first two columns from df
df_first_two_cols = df.iloc[:, :2]
print(df_first_two_cols)

print_sum(5,5,5)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier, plot_tree, export_text
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('/content/attendance_survey.csv')

# Encode text columns to numbers
df['sits_num']      = df['sits_where'].map({'Front':3,'Middle':2,'Back':1})
df['attention_num'] = df['pays_attention'].map({'Always':3,'Sometimes':2,'Rarely':1})
df['doubts_num']    = df['asks_doubts'].map({'Yes':1,'No':0})
df['notes_num']     = df['takes_notes'].map({'Yes':1,'No':0})
df['teacher_num']   = df['teacher_interaction'].map({'Often':3,'Rarely':2,'Never':1})
df['revisit_num']   = df['revisits_class_content'].map({'Always':3,'Sometimes':2,'Never':1})

print("✅ Data ready for ML")
print(f"   {len(df)} students, {len(df.columns)} columns")

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import chi2_contingency
from scipy.stats import f_oneway
from scipy.stats import pearsonr

from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor

sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (8,5)

df = pd.read_csv("/content/attendance_survey.csv")

print("Shape:", df.shape)
df.head()

print(df.info())

print("\nSummary Statistics")
print(df.describe(include='all'))

missing = df.isnull().sum()

print(missing)

plt.figure(figsize=(8,4))
sns.heatmap(df.isnull(), cbar=False)
plt.title("Missing Values")
plt.show()

df=pd.read_csv("/content/attendance_survey.csv")

print(df)

df.head()

df.tail()

print("hello")

