# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ei8I7lJSl0YMDz6Dog8NJMsX-BoylgR1
"""

!pip install mlflow scikit-learn pandas numpy matplotlib -q

import mlflow
import mlflow.sklearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore')

print(f"✅ MLflow version: {mlflow.__version__}")

df = pd.read_csv('/content/attendance_survey.csv')

# Encode
df['sits_num']      = df['sits_where'].map({'Front':3,'Middle':2,'Back':1})
df['attention_num'] = df['pays_attention'].map({'Always':3,'Sometimes':2,'Rarely':1})
df['doubts_num']    = df['asks_doubts'].map({'Yes':1,'No':0})
df['notes_num']     = df['takes_notes'].map({'Yes':1,'No':0})
df['teacher_num']   = df['teacher_interaction'].map({'Often':3,'Rarely':2,'Never':1})
df['revisit_num']   = df['revisits_class_content'].map({'Always':3,'Sometimes':2,'Never':1})

features = ['attendance_pct','sits_num','attention_num',
            'doubts_num','notes_num','teacher_num','revisit_num']

X = df[features]
y = df['marks_pct']

print(f"Dataset: {X.shape[0]} students, {X.shape[1]} features")
print(f"Target : marks_pct (range {y.min():.0f} – {y.max():.0f})")

mlflow.set_experiment("Marks_Prediction")

with mlflow.start_run(run_name="baseline_model"):

    # ── Train the model ────────────────────────────────
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    model = LinearRegression()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    # ── Calculate metrics ──────────────────────────────
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    mae  = mean_absolute_error(y_test, y_pred)
    r2   = r2_score(y_test, y_pred)

    # ── LOG PARAMETERS ─────────────────────────────────
    # Parameters = the SETTINGS you chose before training
    # Things YOU control — test size, which features, etc.
    mlflow.log_param("test_size",     0.2)
    mlflow.log_param("random_state",  42)
    mlflow.log_param("num_features",  len(features))
    mlflow.log_param("model_type",    "LinearRegression")

    # ── LOG METRICS ────────────────────────────────────
    # Metrics = the RESULTS after training
    # Things the model produced — accuracy, error, etc.
    mlflow.log_metric("rmse", round(rmse, 3))
    mlflow.log_metric("mae",  round(mae,  3))
    mlflow.log_metric("r2",   round(r2,   3))

    # ── LOG THE MODEL ──────────────────────────────────
    # Save the actual trained model so you can use it later
    mlflow.sklearn.log_model(model, "linear_regression_model")

    print("=" * 45)
    print("  RUN COMPLETE — Results Logged")
    print("=" * 45)
    print(f"  RMSE  : {rmse:.3f}  ← avg error in marks")
    print(f"  MAE   : {mae:.3f}  ← avg absolute error")
    print(f"  R²    : {r2:.3f}  ← how well model fits")
    print("=" * 45)

with mlflow.start_run(run_name="baseline_with_artifacts"):

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )
    model = LinearRegression()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    mae  = mean_absolute_error(y_test, y_pred)
    r2   = r2_score(y_test, y_pred)

    # Log params & metrics
    mlflow.log_param("test_size",    0.2)
    mlflow.log_param("num_features", len(features))
    mlflow.log_metric("rmse", round(rmse, 3))
    mlflow.log_metric("mae",  round(mae,  3))
    mlflow.log_metric("r2",   round(r2,   3))

    # ── ARTIFACT 1: Actual vs Predicted chart ──────────
    fig, ax = plt.subplots(figsize=(8, 6))
    ax.scatter(y_test, y_pred, color='steelblue',
               alpha=0.7, s=80, edgecolors='navy')
    ax.plot([35,99],[35,99],'r--',linewidth=2,label='Perfect')
    ax.set_xlabel('Actual Marks')
    ax.set_ylabel('Predicted Marks')
    ax.set_title(f'Actual vs Predicted  (R²={r2:.2f})',
                 fontweight='bold')
    ax.legend()
    plt.tight_layout()
    plt.savefig('actual_vs_predicted.png', dpi=150)
    plt.show()
    plt.close()

    # Save chart to MLflow
    mlflow.log_artifact('actual_vs_predicted.png')

    # ── ARTIFACT 2: Feature importance chart ───────────
    coef_df = pd.DataFrame({
        'Feature'    : features,
        'Coefficient': model.coef_
    }).sort_values('Coefficient', ascending=True)

    fig, ax = plt.subplots(figsize=(9, 5))
    colors = ['#2ecc71' if c > 0 else '#e74c3c'
              for c in coef_df['Coefficient']]
    coef_df.plot(kind='barh', x='Feature', y='Coefficient',
                 color=colors, edgecolor='black', ax=ax, legend=False)
    ax.axvline(0, color='black', linewidth=1)
    ax.set_title('Feature Coefficients\n(Green = helps marks, Red = hurts)',
                 fontweight='bold')
    plt.tight_layout()
    plt.savefig('feature_coefficients.png', dpi=150)
    plt.show()
    plt.close()

    mlflow.log_artifact('feature_coefficients.png')

    # ── ARTIFACT 3: Predictions CSV ────────────────────
    results_df = pd.DataFrame({
        'Actual'    : y_test.values,
        'Predicted' : y_pred.round(1),
        'Error'     : abs(y_test.values - y_pred).round(1)
    })
    results_df.to_csv('predictions.csv', index=False)
    mlflow.log_artifact('predictions.csv')

    mlflow.sklearn.log_model(model, "model")

    print("✅ Run complete — params, metrics, charts, CSV all saved")

# Experiment configurations to try
experiments = [
    {
        "run_name"   : "all_features_20split",
        "features"   : features,
        "test_size"  : 0.2,
        "description": "All 7 features, 80-20 split"
    },
    {
        "run_name"   : "all_features_30split",
        "features"   : features,
        "test_size"  : 0.3,
        "description": "All 7 features, 70-30 split"
    },
    {
        "run_name"   : "top3_features",
        "features"   : ['attendance_pct','attention_num','teacher_num'],
        "test_size"  : 0.2,
        "description": "Only top 3 features"
    },
    {
        "run_name"   : "attendance_only",
        "features"   : ['attendance_pct'],
        "test_size"  : 0.2,
        "description": "Attendance alone — baseline"
    },
    {
        "run_name"   : "no_attendance",
        "features"   : ['sits_num','attention_num','doubts_num',
                        'notes_num','teacher_num','revisit_num'],
        "test_size"  : 0.2,
        "description": "All habits — NO attendance"
    }
]

print("Running 5 experiments...\n")
print(f"{'Run':<30} {'Features':>10} {'RMSE':>8} {'R²':>8}")
print("-" * 60)

for exp in experiments:
    with mlflow.start_run(run_name=exp["run_name"]):

        X_exp = df[exp["features"]]
        X_tr, X_te, y_tr, y_te = train_test_split(
            X_exp, y,
            test_size=exp["test_size"],
            random_state=42
        )

        model = LinearRegression()
        model.fit(X_tr, y_tr)
        y_pred = model.predict(X_te)

        rmse = round(np.sqrt(mean_squared_error(y_te, y_pred)), 3)
        mae  = round(mean_absolute_error(y_te, y_pred), 3)
        r2   = round(r2_score(y_te, y_pred), 3)

        # Log everything
        mlflow.log_param("features",    str(exp["features"]))
        mlflow.log_param("num_features",len(exp["features"]))
        mlflow.log_param("test_size",   exp["test_size"])
        mlflow.log_param("description", exp["description"])
        mlflow.log_metric("rmse", rmse)
        mlflow.log_metric("mae",  mae)
        mlflow.log_metric("r2",   r2)
        mlflow.sklearn.log_model(model, "model")

        print(f"{exp['run_name']:<30} {len(exp['features']):>10} "
              f"{rmse:>8} {r2:>8}")

print("\n✅ All 5 runs logged to MLflow")

# Pull all runs from MLflow and compare
runs = mlflow.search_runs(
    experiment_names=["Marks_Prediction"],
    order_by=["metrics.rmse ASC"]
)

# Clean display
display_cols = ['tags.mlflow.runName',
                'params.num_features',
                'params.test_size',
                'metrics.rmse',
                'metrics.r2',
                'metrics.mae']

compare_df = runs[display_cols].copy()
compare_df.columns = ['Run Name','Num Features',
                      'Test Size','RMSE','R²','MAE']

print("ALL RUNS — Best to Worst (sorted by RMSE ↑)\n")
print(compare_df.to_string(index=False))

best = compare_df.iloc[0]
print(f"\n🏆 BEST RUN : {best['Run Name']}")
print(f"   RMSE     : {best['RMSE']}")
print(f"   R²       : {best['R²']}")

import subprocess, time

# Start MLflow
subprocess.Popen(
    ["mlflow", "ui", "--port", "5000", "--host", "0.0.0.0"],
    stdout=subprocess.DEVNULL,
    stderr=subprocess.DEVNULL
)
time.sleep(3)

# Install and start localtunnel — no account needed
!npm install -g localtunnel -q

# Run in background and grab the URL
result = subprocess.Popen(
    ["lt", "--port", "5000"],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE
)
time.sleep(3)

url_line = result.stdout.readline().decode()
print(f"✅ MLflow UI → {url_line.strip()}")
print("\n⚠️  If it asks for a password — enter your Colab IP")
print("   Get your IP by running:  !curl ifconfig.me")

